server:
  port: 8084
spring:
  application:
    name: smart-message
  cloud:
    nacos:
      discovery:
        server-addr:    # Nacos ??
        username: nacos               # ?? Nacos ????????
        password: nacos

